//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Inventory_DBEntities : DbContext
    {
        public Inventory_DBEntities()
            : base("name=Inventory_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item_Master> Item_Master { get; set; }
    
        public virtual ObjectResult<string> USP_Del_Item(Nullable<int> item_ID)
        {
            var item_IDParameter = item_ID.HasValue ?
                new ObjectParameter("Item_ID", item_ID) :
                new ObjectParameter("Item_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_Del_Item", item_IDParameter);
        }
    
        public virtual ObjectResult<USP_Get_Item_Result> USP_Get_Item(Nullable<int> item_ID)
        {
            var item_IDParameter = item_ID.HasValue ?
                new ObjectParameter("Item_ID", item_ID) :
                new ObjectParameter("Item_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_Item_Result>("USP_Get_Item", item_IDParameter);
        }
    
        public virtual ObjectResult<string> USP_Ins_Item(Nullable<int> item_ID, string item_Name, Nullable<decimal> price, string description, Nullable<int> add_By)
        {
            var item_IDParameter = item_ID.HasValue ?
                new ObjectParameter("Item_ID", item_ID) :
                new ObjectParameter("Item_ID", typeof(int));
    
            var item_NameParameter = item_Name != null ?
                new ObjectParameter("Item_Name", item_Name) :
                new ObjectParameter("Item_Name", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var add_ByParameter = add_By.HasValue ?
                new ObjectParameter("Add_By", add_By) :
                new ObjectParameter("Add_By", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_Ins_Item", item_IDParameter, item_NameParameter, priceParameter, descriptionParameter, add_ByParameter);
        }
    }
}
